### ISSUE TITLE
weird behavior in Load/Debit Ops

### ISSUE THREAD

**Issue by Andres1012** [eclipse/keyple-cpp-example#2]
When I do operations of load / debit with any value repeatedly, the balance in the card change correctly sometimes but in another times the last bytes change “00” to “FF” or "FF" to "00".

![image](https://user-images.githubusercontent.com/16720540/229018529-79835bf7-2540-4759-a6e2-a50e00db9bed.png)

For example, in the image you can see the balance before changed to negative value is 5221(decimal) = 0x1465 (hexadecimal), after the load 100 the balance change to: -16771895 (decimal) = 0xFF0014C9 (hexadecimal). If you change last byte to zero the value is 5321 (decimal) = 0x**00**0014C9.

The code I use is based of example code UseCase10_SessionTrace_TN313 and UseCase7_StoredValue_SimpleReloading:

`          {
            /*
             * Read the current time used later to compute the transaction time.
             */
            auto calypsoCard =
                std::dynamic_pointer_cast<CalypsoCard>(
                    mCardSelectionManager
                        ->parseScheduledCardSelectionsResponse(
                            event->getScheduledCardSelectionsResponse())
                        ->getActiveSmartCard());

            /*
             * Create a transaction manager, prepare SV Get.
             */
            std::shared_ptr<CardTransactionManager> cardTransactionManager =
                 CalypsoExtensionService::getInstance()
                    ->createCardTransaction(mCardReader, calypsoCard, mCardSecuritySetting);
            cardTransactionManager->prepareSvGet(SvOperation::RELOAD, SvAction::DO)
            		.processCommands();

            int amount = calypsoCard->getSvLoadLogRecord()->getAmount();
            int balance = calypsoCard->getSvBalance();

            mLogger->info("Balance: %\n", balance);
            mLogger->info("amount: %\n", amount);
            cardTransactionManager->prepareSvReload(2).processCommands();

            balance = calypsoCard->getSvBalance();
            amount = calypsoCard->getSvLoadLogRecord()->getAmount();

            mLogger->info("Balance: %\n", balance);
            mLogger->info("amount: %\n", amount);

            /* Display transaction time */
            mLogger->info("%Transaction succeeded. Execution time: % ms%\n",
                          ANSI_GREEN,
                          System::currentTimeMillis() - timeStamp,
                          ANSI_RESET);
}
        `

**Comment by jeanpierrefortune** [comment]
Hi Andres1012,
Thank you for reporting this issue.
This seems to be related to the conversion of the value stored in the card (3 signed bytes) to an integer.
At first glance, the operation with the card is correct since the balance value seems to increase as expected.
I will investigate the issue and get back to you.

**Comment by al3xwq** [comment]
Hi @Andres1012,

The problem was in fact in the ByteArrayUtil::extractInt() function from keyple-util-cpp-lib.

Please update to version 2.3.0.3 and confirm it works on your end.

Thanks!
Alex

**Comment by Andres1012** [comment]
Great news!
I'm going to try it.
 Thanks!
